name: Multi-Stage Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Stage 1: Build
      - name: Build project
        run: |
          echo "Building project..."
          # Add build commands here

      # Stage 2: Test
      - name: Run tests
        run: |
          echo "Running tests..."
          # Add test commands here

      # Stage 3: Deploy
      - name: Deploy to dev
        run: |
           echo "Deploying...."

