name: Multi-Stage Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Build project
        run: |
          echo "Building project..."
          # Add build commands here
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Run tests
        run: |
          echo "Running tests..."
          # Add test commands here
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Deploy to dev
        run: |
           echo "Deploying...."

